In [2]:
import numpy as np
import pandas as pd


In [2]:
a = np.int8(25)

In [3]:
print(type(a))

<class 'numpy.int8'>


In [12]:
np.iinfo(np.int64)
# np.iinfo(a)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [13]:
b = np.uint8(124)
print(b)
# 124
print(type(b))
# <class 'numpy.uint8'>
np.iinfo(b)

124
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

In [16]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
# 2147483610 2147483605
print(a + b)



2147483610 2147483605
-81


C:\Users\Павел\AppData\Local\Temp\ipykernel_19420\3438126313.py:5: RuntimeWarning: overflow encountered in long_scalars
  print(a + b)


In [17]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
# 2147483610 2147483605
print(np.int64(a) + np.int64(b))

2147483610 2147483605
4294967215


In [19]:
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.intc'>
<class 'numpy.longdouble'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.uintc'>
<class 'numpy.void'>


In [23]:
a = -456
a = np.uint8(-456)
np.iinfo(a)

iinfo(min=0, max=255, dtype=uint8)

In [16]:
arr = np.array([126,15,102,109,10], dtype=np.uint8)

In [30]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [31]:
print(arr.itemsize)
print(nd_arr.shape)



1
(3, 3)


In [34]:
zeros_1d = np.zeros(5)
zeros_1d[1] = 100
zeros_1d
zeros_1d.dtype



dtype('float64')

In [36]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)
zeros_3d

(5, 4, 3)


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [42]:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5  , 2.7  , 2.898, 3.098, 3.297, 3.496, 3.695, 3.895, 4.094,
       4.293, 4.492, 4.69 , 4.89 ], dtype=float16)

In [44]:
arr1 = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
arr1

(array([-6.  , -5.55, -5.1 , -4.65, -4.2 , -3.75, -3.3 , -2.85, -2.4 ,
        -1.95, -1.5 , -1.05, -0.6 , -0.15,  0.3 ,  0.75,  1.2 ,  1.65,
         2.1 ,  2.55,  3.  ,  3.45,  3.9 ,  4.35,  4.8 ,  5.25,  5.7 ,
         6.15,  6.6 ,  7.05,  7.5 ,  7.95,  8.4 ,  8.85,  9.3 ,  9.75,
        10.2 , 10.65, 11.1 , 11.55, 12.  , 12.45, 12.9 , 13.35, 13.8 ,
        14.25, 14.7 , 15.15, 15.6 , 16.05, 16.5 , 16.95, 17.4 , 17.85,
        18.3 , 18.75, 19.2 , 19.65, 20.1 , 20.55]),
 0.45)

In [61]:
vec1 = np.array([3, 5, 8])
lenght = np.sqrt(np.sum(vec1**2))
print(lenght)

9.899494936611665


In [63]:
lenght1 = np.linalg.norm(vec1)
lenght1

9.899494936611665

In [64]:
vec2 = np.array([10, 87, 0])

In [67]:
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance

82.68615361715648

In [68]:
distance1 = np.linalg.norm(vec1 - vec2)
distance1

82.68615361715648

In [70]:
vec3 = np.arange(1, 6)
vec4 = np.linspace(1, 20, 5)

In [71]:
scalar1 = np.sum(vec3 * vec4)
scalar1

205.0

In [72]:
scalar2 = np.dot(vec3, vec4)
scalar2

205.0

In [73]:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)

0

In [104]:
round(np.arange(2.5, 5, 0.2, dtype=np.float16), 2)

TypeError: type numpy.ndarray doesn't define __round__ method

In [93]:
np.random.seed(24)
np.random.randint(10, size=(3,4))

array([[2, 3, 0, 7],
       [1, 1, 1, 4],
       [4, 3, 2, 3]])

In [99]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))

[8 8 3]
[7 7 0]
[4 2 5]


In [102]:
np.random.uniform(2, 17, size = 8)

array([11.36467832,  9.85021616, 10.43444397,  2.08725787,  6.61134817,
       16.25276471,  3.89981358,  3.18481809])

In [106]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [6]:
table = np.random.randint(1, 101, size=(3,2))
table

array([[86, 36],
       [68, 60],
       [85, 85]])

# 10.6


In [ ]:
import numpy as np
def get_chess(a):
    arr = np.zero((a,a))
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr
print(get_chess(5))


# 10.7

In [123]:
import numpy as np
def shuffle_seed(array):
    seed = np.random.randint(2**32)
    np.random.seed(seed)
    shuffled = np.random.permutation(array)
    return shuffled, seed
a= np.array([1, 6, 7, 9, 20, 17])
shuffle_seed(a)
    

(array([ 6, 17,  9, 20,  7,  1]), 3543566986)

# 10.8

In [125]:
import numpy as np
def min_max_dist(*vectors):
    dist =list()
    for i in range(len(vectors)):
        for j in range(i+1, len(vectors)):
            dist.append(np.linalg.norm(vectors[i]- vectors[j]))
    return (min(dist)), (max(dist))

In [126]:
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
 
min_max_dist(vec1, vec2, vec3)

(5.196152422706632, 10.392304845413264)

# 10.9

In [132]:
import numpy as np
def any_normal(*vectors):
    for i in range(len(vectors)):
        for j in range(i+1, len(vectors)):
            if np.dot(vectors[i], vectors[j]) == 0:
                return True
    return False

In [134]:
vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))

True


# 10.10

In [145]:
import numpy as np
def get_loto(num):
    arr = np.random.randint(1,101, size= (num, 5, 5))
    return arr
    

In [146]:
get_loto(3)

array([[[24, 45, 67, 85, 34],
        [49, 76, 19, 46,  4],
        [77, 89, 90, 40, 42],
        [68, 39, 12, 31, 56],
        [85, 22, 28, 64, 52]],

       [[45, 91, 10, 32,  1],
        [76, 82, 90,  8, 99],
        [61, 42, 10, 39, 58],
        [15, 72, 40,  8, 69],
        [86, 33, 38, 13, 89]],

       [[96, 53, 60,  2, 13],
        [89, 65, 83, 79, 19],
        [77, 52, 28, 30, 88],
        [85, 34, 94, 42,  6],
        [13, 69, 97, 88, 96]]])

# 10.11


In [164]:
import numpy as np
def get_unique_loto(num):
    ary = np.arange(1,101)
    res= list()
    for i in range(num):
        res.append(np.random.choice(ary, size= (5, 5), replace=False))
    res = np.array(res)
    return res
get_unique_loto(10)

array([[[ 40,  44,  64,  45,  39],
        [  8,  30,  26,  67,  91],
        [ 12,  21,  99,  92,  31],
        [  9,  89,  75,  88,  58],
        [ 22,  62,  41, 100,  24]],

       [[ 39,  28,  34,  10,  60],
        [ 92,   9,  12, 100,  76],
        [ 35,  70,   1,   2,  54],
        [ 63,  31,  95,   8,  84],
        [ 97,  23,  25,  40,  93]],

       [[ 42,  43,  98,   3,  86],
        [ 25,  39,  78,  69,  61],
        [ 77,  96,  40,  37,  30],
        [ 62,  52,  45,  38,  28],
        [ 90,  47,  93,  68,  59]],

       [[  9,  18,  68,  98,  74],
        [ 11,  97,  91,  23,  95],
        [ 36, 100,  82,  88,  46],
        [ 99,  77,  85,  16,  32],
        [ 61,  66,  10,  64,  92]],

       [[ 36,  91,  74,  59,  26],
        [ 96,  31,  35,  51,   8],
        [ 93,  99,   1,   2,  69],
        [ 27,  77,  67,  22,  41],
        [ 71,   7,  76,  49,  28]],

       [[  6,  43,  49,  66,  53],
        [  8,  97,  51,  16,  47],
        [  5,  89,  48,  36,  38],
        [ 

In [170]:
simplelist = [19, 242, 14, 152, 142, 1000]
a= np.array(simplelist)
b = np.mean(a)
b

261.5